algoritmo "Idade"

var
   Nome1, Nome2: caractere
   Idade1, Idade2: inteiro
   media: real
   
inicio
      escreval("Dadod da primeira pessoal")
      escreval("Digite nome: ")
      leia(Nome1)
      Escreval("Digite idade: ")
      leia(Idade1)
      
      Escreval
      
      Escreval ("Dados da Segunda Pessoal")
      Escreval("Digite nome: ")
      leia(Nome2)
      Escreval("Digite Idade: ")
      Leia(Idade2)
      
      escreval
      
      media <- (Idade1 + Idade2) / 2
      Escreval (" A idade média de ",Nome1, " e ",Nome2, "é de ",media:4:1, " anos")
fimalgoritmo
