algoritmo "nota"

var
   primeiraNota, segundaNota, notaFinal: real

inicio

      Escreval("======= NOTA DO ANO LETIVO ======= ")
      Escreval("Digite sua primeira nota: ")
      leia(primeiraNota)
      Escreval
      Escreval("Digite sua primeira nota: ")
      leia(segundaNota)
      Escreval
      notaFinal <- (primeiraNota + SegundaNota) /2:4:1
      Escreval ("Nota Final = ", notaFinal)
      se notaFinal >= 6 entao
         Escreval ("Aprovado")
      senao
         Escreval ("Reprovado")
      fimse
fimalgoritmo
