algoritmo "Crescente"

var
   x,y : inteiro

inicio
        Escreval("Digite Dois Numeros")
             Leia (x)
             Leia (y)

      enquanto x <> y faca

             se x > y entao
                Escreval("Decrescente")
             senao
                Escreval ("Crescente")
             fimse
             Escreval("Digite outros Dois Numeros")
             Leia (x)
             Leia (y)
     Fimenquanto

fimalgoritmo
