Algoritmo "paresConsecutivos"

Var
   x, soma : inteiro
Inicio
      ESCREVA("DIGITE UM NUMERO INTEIRO: ")
      LEIA(X)
      
      ENQUANTO X <> 0 FACA

             SE X % 2 <> 0 ENTAO
                X <- X + 1
             FIMSE
             
             SOMA <- 5 * X + 20
             ESCREVAL ("SOMA = ", SOMA)
             
             ESCREVA("DIGITE UM NUMERO INTEIRO: ")
             LEIA(X)

      FIMENQUANTO

Fimalgoritmo
