Algoritmo "Media_ponderada"

Var
   i, N: INTEIRO
   media, n1, n2, n3: real
Inicio
      ESCREVA("Quantos numeros voce vai digitar? ")
      leia(N)
      
      para i de 1 ate N faca
      
          escreval("Digite tres numeros: ")
          leia(n1)
          leia(n2)
          leia(n3)
          rrrr
          media <- (n1 * 2 + n2 * 3 + n3 * 5)/10
          Escreval("Media = ",media:2:1)
      fimpara
      
Fimalgoritmo