algoritmo "pagamento"

var

   nome: caractere
   valor, pg: real
   Horas: inteiro

inicio

      escreval("=======Folha de pagamento=======")
      escreval("Digite nome do Funcionario:")
      leia(nome)
      Escreval("Valor por hora:")
      leia(valor)
      Escreval("Horas trabalhadas")
      leia(Horas)
      
      pg <- valor * horas
      
      escreval ("O pagamento para ", nome, " deve ser ",pg:8:2)
      
      

fimalgoritmo
